apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-alpine
  labels:
    app: apline
    lab: "4.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
      lab: "4.1"
  template:
    metadata:
      labels:
        app: alpine
        lab: "4.1"
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo-service-v1
spec:
  selector:
    lab: "podinfo-1"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80