apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: webui
      port: {{ .Values.sevicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
  selector:
    app: foundry
    game: dannysfolly
  type: NodePort
