apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: dev
  name: dev

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "8Gi"

---
apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: dev
spec:
  limits:
    - default: # this section defines default limits
        cpu: 500m
        memory: 512Mi
      defaultRequest: # this section defines default requests
        cpu: 100m
        memory: 128Mi
      type: Container
